"""empty message

Revision ID: b21b6a3be38d
Revises: e2c86ad35888
Create Date: 2021-05-12 02:18:26.092971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21b6a3be38d'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chassis_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('system', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('numberpart', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chassis_parts')
    # ### end Alembic commands ###
