"""empty message

Revision ID: e37c3f293bb2
Revises: 407042d83ac0
Create Date: 2021-05-16 23:49:15.884203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37c3f293bb2'
down_revision = '407042d83ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('enlace', sa.String(length=1024), nullable=False))
    op.add_column('product', sa.Column('cardid', sa.Integer(), nullable=False))
    op.drop_column('product', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_column('product', 'cardid')
    op.drop_column('product', 'enlace')
    # ### end Alembic commands ###
